[server]
headless = true
enableCORS = false

[client]
toolbarMode = "minimal"
showErrorDetails = false

[theme]
primaryColor = "#005a8d"
backgroundColor = "#f4f8fc"
secondaryBackgroundColor = "#ffffff"
textColor = "#0b1f35"
font = "sans serif"

[global]
unit = "metric"
